frase = str(input('Digite uma frase: ')).strip()
frasel = frase.lower()
a = frasel.count('a')
print()
print('"{}" contem {} letras "a"'.format(frase, a))
a1 = frasel.find('a')
print('A primeira letra "a" aparece na posição "{}"'.format(a1+1))
a2 = frasel.rfind('a')
print('A ultima letra "a" aparece na posição "{}"'.format(a2+1))
