nome = str(input('Digite seu nome completo: ')).strip()
nome = nome.title()
nsplit = nome.split()
print()
print('Nome completo: {}'.format(nome))
print()
print('Primeiro nome: {}'.format(nsplit[0]))
print()
print('Ultimo nome: {}'.format(nsplit[-1]))
