nome = str(input('Digite seu nome completo: ')).strip()
nome = nome.title()
print()
print('Nome em maiúsculo: {}'.format(nome.upper()))
print()
print('Nome em minúsculo: {}'.format(nome.lower()))
print()
print('{} sem considerar os espaços, tem {} letras ao todo!'.format(nome,len(nome.replace(' ',''))))
print()
nomesplit = nome.split()
print('Seu primeiro nome é {}, e tem {} letras!'.format(nomesplit[0],len(nomesplit[0])))
